### ISSUE TITLE
希望出题可以加入连加，连减，加减综合的选项，谢谢~

### ISSUE THREAD

**Issue by mtojason** [NMTuan/maths#4]
希望出题可以加入连加，连减，加减综合的选项，谢谢！

**Comment by NMTuan** [comment]
连加. 连减, 是特指三组数字的加减法. 还是可以4组.5组.之类的. 
另外, 加减综合是什么意思..

孩子还没上学, 这些东西我都不太了解. 能否给举几个例子.

**Comment by NMTuan** [comment]
连加和连减功能已添加。希望能帮到你。

加减综合我再考虑考虑

**Comment by mtojason** [comment]
很抱歉，这几天一直在外，没有及时关注github注册的邮箱，所以没能及时回复。我的孩子也还没上学，最近也是在做买的习题册。连加，连减的意思是几个数字连续做加法或者减法，例如：5+6+4，9-5-1；综合的意思是几个数字之间既有加法也有减法，例如：8-5+2，5+1-5，希望这个解释能理解，谢谢！
