### ISSUE TITLE
打开index.html是空白页面

### ISSUE THREAD

**Issue by wuge0** [NMTuan/maths#6]

**Comment by NMTuan** [comment]
请访问 docs/index.html 文件

**Comment by wuge0** [comment]
好的 我试试

**Comment by wuge0** [comment]
可以访问了，请问如何在规则里添加 去 编号 括号 下横线
50题可以改成自定义吗

**Comment by NMTuan** [comment]
都有注释, 自行查找.

**Comment by wuge0** [comment]
> 请访问 docs/index.html 文件


没找到注释
调用的js也不会改啊大佬`docs\assets\index.c5d80f41.js`

**Comment by NMTuan** [comment]
> > 请访问 docs/index.html 文件
> 
> 没找到注释 调用的js也不会改啊大佬`docs\assets\index.c5d80f41.js`

这个项目属于工程化的前端项目. 先了解下svelte框架和vite吧.
